### ISSUE TITLE
Continuous scrolling

### ISSUE THREAD

**Issue by ghost** [Borisvl/Pdf4Eclipse#2]
Hi Boris,

is it possible to add a continous sdcrolling feature in your plugin? I really like it and it is so far the only missing feature I found.

Bye,
domasz

**Comment by Borisvl** [comment]
Yes, this is definitely a feature that would be nice. However, it is a little bit more complicated to implement, but I will look into it.

**Comment by ghost** [comment]
Great, thank you very much!

CU,
Thomas

On 10.11.2011, at 14:23, Boris von Loesch wrote:

> Yes, this is definitely a feature that would be nice. However, it is a little bit more complicated to implement, but I will look into it.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Borisvl/Pdf4Eclipse/issues/2#issuecomment-2695106

---

Dipl. Phys. Thomas Weber

Erlangen Centre for Astroparticle Physics (ECAP)
Novel Detectors / Medical Physics

University of Erlangen-Nuremberg
Erwin-Rommel-Str. 1
91058 Erlangen

e-mail:   thomas.weber@physik.uni-erlangen.de 
web:   http://www.ecap.nat.uni-erlangen.de/novel
phone:  +49-(0)-9131-85-27124
fax:    +49-(0)-9131-15249

**Comment by jenom** [comment]
Yeah I agree, this is an important feature. Otherwise this is superior in usability as a preview compared to external viewers. Thank you very much. An idea for the continious scrolling: You do not need to render two pages but instead open the next, when it reaches the end of the previous one. I think xpdf has this behaviour. It should be much easier to implement.

**Comment by scout0074** [comment]
Great tool so far, thank you very much!

I agree with jenom. Showing the next or previous page would be more than enough for now. Even two buttons (previous / next page) would be fine, which might not be a big deal since the page selection by page number within the status bar is working fine.

By
scout

**Comment by arighauks** [comment]
First of all, thank you I would very much for pdf4eclipse, I love it so far.

I would however like to be able to scroll in the document (which would pretty much make it perfect imo =)

Thanks, and keep up the great work!!

**Comment by teake** [comment]
+1 on the scrolling. Btw thanks for writing pdf4eclipse, it's much more convenient than external PDF viewers.

**Comment by damjankuznar** [comment]
Another +1 for this feature.

**Comment by francoisvdv** [comment]
Thanks for this great tool, use it a lot. I'd really like this feature though - so +1 from me as well.

**Comment by Borisvl** [comment]
I added pseudo continuous scrolling in the latest version (1.0.2). This should be much better for many users.

**Comment by teake** [comment]
Thanks!

**Comment by damjankuznar** [comment]
Not perfect but still much better than before. Thanks.

**Comment by ghost** [comment]
Thanks! That's now totally fine!

**Comment by rasvaan** [comment]
Thank you!

**Comment by francoisvdv** [comment]
Definitely much better, thanks!
