### ISSUE TITLE
backward search

### ISSUE THREAD

**Issue by kokorins** [Borisvl/Pdf4Eclipse#6]
The double click on pdf at any place tells me that "path to file" doesn't exist.
It seems that double clicking on the pdf tries to search in the same directory, though I got a lot of subfolders, separated result pdf and source tex files folders. The structure is something like that:
bin  -- for pdf
src/ -- for tex files
    chapter1/
    chapter2/

**Comment by Borisvl** [comment]
This should not be a problem, but maybe pdf4eclipse does not parse the synctex file correctly. If you send me a test project with a pdf and the corresponding synctex file I will take a look at it.

**Comment by kokorins** [comment]
Hm. I've created the default project with setup bin, src directories. After the double click I got message: Source file [path to bin]/test.tex does not exist. I forgot to mention, that I use ubuntu 11.10, eclipse indigo, texclipse 1.5, and pdf4eclipse 1.0.1

PS it seems that I cant attach any files.

**Comment by Borisvl** [comment]
The problem is, that the Latex distribution you use writes only relative file names into the .synctex file. If the output file is moved to the out directory, it searches your files at the wrong place. You must have the same problems when you use an external pdf viewer. Which Latex distribution are you using?

One possible workaround is to choose no "src" and "out" folder in your TeXlipse project.
